# SPDX-License-Identifier: MIT OR GPL-3.0-or-later
from collections.abc import Mapping
from typing import Final

from ..vrm1.human_bone import HumanBoneSpecification, HumanBoneSpecifications

DEFAULT_MAPPING: Final[Mapping[str, HumanBoneSpecification]] = {
    "eye.R": HumanBoneSpecifications.RIGHT_EYE,
    "eye.L": HumanBoneSpecifications.LEFT_EYE,
    "jaw": HumanBoneSpecifications.JAW,
    "head": HumanBoneSpecifications.HEAD,
    "neck01": HumanBoneSpecifications.NECK,
    "spine02": HumanBoneSpecifications.UPPER_CHEST,
    "spine03": HumanBoneSpecifications.CHEST,
    "spine04": HumanBoneSpecifications.SPINE,
    "root": HumanBoneSpecifications.HIPS,
    "shoulder01.R": HumanBoneSpecifications.RIGHT_SHOULDER,
    "upperarm01.R": HumanBoneSpecifications.RIGHT_UPPER_ARM,
    "lowerarm01.R": HumanBoneSpecifications.RIGHT_LOWER_ARM,
    "wrist.R": HumanBoneSpecifications.RIGHT_HAND,
    "shoulder01.L": HumanBoneSpecifications.LEFT_SHOULDER,
    "upperarm01.L": HumanBoneSpecifications.LEFT_UPPER_ARM,
    "lowerarm01.L": HumanBoneSpecifications.LEFT_LOWER_ARM,
    "wrist.L": HumanBoneSpecifications.LEFT_HAND,
    "upperleg01.R": HumanBoneSpecifications.RIGHT_UPPER_LEG,
    "lowerleg01.R": HumanBoneSpecifications.RIGHT_LOWER_LEG,
    "foot.R": HumanBoneSpecifications.RIGHT_FOOT,
    "upperleg01.L": HumanBoneSpecifications.LEFT_UPPER_LEG,
    "lowerleg01.L": HumanBoneSpecifications.LEFT_LOWER_LEG,
    "foot.L": HumanBoneSpecifications.LEFT_FOOT,
    "finger1-1.R": HumanBoneSpecifications.RIGHT_THUMB_METACARPAL,
    "finger1-2.R": HumanBoneSpecifications.RIGHT_THUMB_PROXIMAL,
    "finger1-3.R": HumanBoneSpecifications.RIGHT_THUMB_DISTAL,
    "finger2-1.R": HumanBoneSpecifications.RIGHT_INDEX_PROXIMAL,
    "finger2-2.R": HumanBoneSpecifications.RIGHT_INDEX_INTERMEDIATE,
    "finger2-3.R": HumanBoneSpecifications.RIGHT_INDEX_DISTAL,
    "finger3-1.R": HumanBoneSpecifications.RIGHT_MIDDLE_PROXIMAL,
    "finger3-2.R": HumanBoneSpecifications.RIGHT_MIDDLE_INTERMEDIATE,
    "finger3-3.R": HumanBoneSpecifications.RIGHT_MIDDLE_DISTAL,
    "finger4-1.R": HumanBoneSpecifications.RIGHT_RING_PROXIMAL,
    "finger4-2.R": HumanBoneSpecifications.RIGHT_RING_INTERMEDIATE,
    "finger4-3.R": HumanBoneSpecifications.RIGHT_RING_DISTAL,
    "finger5-1.R": HumanBoneSpecifications.RIGHT_LITTLE_PROXIMAL,
    "finger5-2.R": HumanBoneSpecifications.RIGHT_LITTLE_INTERMEDIATE,
    "finger5-3.R": HumanBoneSpecifications.RIGHT_LITTLE_DISTAL,
    "finger1-1.L": HumanBoneSpecifications.LEFT_THUMB_METACARPAL,
    "finger1-2.L": HumanBoneSpecifications.LEFT_THUMB_PROXIMAL,
    "finger1-3.L": HumanBoneSpecifications.LEFT_THUMB_DISTAL,
    "finger2-1.L": HumanBoneSpecifications.LEFT_INDEX_PROXIMAL,
    "finger2-2.L": HumanBoneSpecifications.LEFT_INDEX_INTERMEDIATE,
    "finger2-3.L": HumanBoneSpecifications.LEFT_INDEX_DISTAL,
    "finger3-1.L": HumanBoneSpecifications.LEFT_MIDDLE_PROXIMAL,
    "finger3-2.L": HumanBoneSpecifications.LEFT_MIDDLE_INTERMEDIATE,
    "finger3-3.L": HumanBoneSpecifications.LEFT_MIDDLE_DISTAL,
    "finger4-1.L": HumanBoneSpecifications.LEFT_RING_PROXIMAL,
    "finger4-2.L": HumanBoneSpecifications.LEFT_RING_INTERMEDIATE,
    "finger4-3.L": HumanBoneSpecifications.LEFT_RING_DISTAL,
    "finger5-1.L": HumanBoneSpecifications.LEFT_LITTLE_PROXIMAL,
    "finger5-2.L": HumanBoneSpecifications.LEFT_LITTLE_INTERMEDIATE,
    "finger5-3.L": HumanBoneSpecifications.LEFT_LITTLE_DISTAL,
}

GAME_ENGINE_MAPPING: Final[Mapping[str, HumanBoneSpecification]] = {
    "head": HumanBoneSpecifications.HEAD,
    "neck_01": HumanBoneSpecifications.NECK,
    "spine_03": HumanBoneSpecifications.UPPER_CHEST,
    "spine_02": HumanBoneSpecifications.CHEST,
    "spine_01": HumanBoneSpecifications.SPINE,
    "pelvis": HumanBoneSpecifications.HIPS,
    "clavicle_r": HumanBoneSpecifications.RIGHT_SHOULDER,
    "upperarm_r": HumanBoneSpecifications.RIGHT_UPPER_ARM,
    "lowerarm_r": HumanBoneSpecifications.RIGHT_LOWER_ARM,
    "hand_r": HumanBoneSpecifications.RIGHT_HAND,
    "clavicle_l": HumanBoneSpecifications.LEFT_SHOULDER,
    "upperarm_l": HumanBoneSpecifications.LEFT_UPPER_ARM,
    "lowerarm_l": HumanBoneSpecifications.LEFT_LOWER_ARM,
    "hand_l": HumanBoneSpecifications.LEFT_HAND,
    "thigh_r": HumanBoneSpecifications.RIGHT_UPPER_LEG,
    "calf_r": HumanBoneSpecifications.RIGHT_LOWER_LEG,
    "foot_r": HumanBoneSpecifications.RIGHT_FOOT,
    "ball_r": HumanBoneSpecifications.RIGHT_TOES,
    "thigh_l": HumanBoneSpecifications.LEFT_UPPER_LEG,
    "calf_l": HumanBoneSpecifications.LEFT_LOWER_LEG,
    "foot_l": HumanBoneSpecifications.LEFT_FOOT,
    "ball_l": HumanBoneSpecifications.LEFT_TOES,
    "thumb_01_l": HumanBoneSpecifications.LEFT_THUMB_METACARPAL,
    "thumb_02_l": HumanBoneSpecifications.LEFT_THUMB_PROXIMAL,
    "thumb_03_l": HumanBoneSpecifications.LEFT_THUMB_DISTAL,
    "index_01_l": HumanBoneSpecifications.LEFT_INDEX_PROXIMAL,
    "index_02_l": HumanBoneSpecifications.LEFT_INDEX_INTERMEDIATE,
    "index_03_l": HumanBoneSpecifications.LEFT_INDEX_DISTAL,
    "middle_01_l": HumanBoneSpecifications.LEFT_MIDDLE_PROXIMAL,
    "middle_02_l": HumanBoneSpecifications.LEFT_MIDDLE_INTERMEDIATE,
    "middle_03_l": HumanBoneSpecifications.LEFT_MIDDLE_DISTAL,
    "ring_01_l": HumanBoneSpecifications.LEFT_RING_PROXIMAL,
    "ring_02_l": HumanBoneSpecifications.LEFT_RING_INTERMEDIATE,
    "ring_03_l": HumanBoneSpecifications.LEFT_RING_DISTAL,
    "pinky_01_l": HumanBoneSpecifications.LEFT_LITTLE_PROXIMAL,
    "pinky_02_l": HumanBoneSpecifications.LEFT_LITTLE_INTERMEDIATE,
    "pinky_03_l": HumanBoneSpecifications.LEFT_LITTLE_DISTAL,
    "thumb_01_r": HumanBoneSpecifications.RIGHT_THUMB_METACARPAL,
    "thumb_02_r": HumanBoneSpecifications.RIGHT_THUMB_PROXIMAL,
    "thumb_03_r": HumanBoneSpecifications.RIGHT_THUMB_DISTAL,
    "index_01_r": HumanBoneSpecifications.RIGHT_INDEX_PROXIMAL,
    "index_02_r": HumanBoneSpecifications.RIGHT_INDEX_INTERMEDIATE,
    "index_03_r": HumanBoneSpecifications.RIGHT_INDEX_DISTAL,
    "middle_01_r": HumanBoneSpecifications.RIGHT_MIDDLE_PROXIMAL,
    "middle_02_r": HumanBoneSpecifications.RIGHT_MIDDLE_INTERMEDIATE,
    "middle_03_r": HumanBoneSpecifications.RIGHT_MIDDLE_DISTAL,
    "ring_01_r": HumanBoneSpecifications.RIGHT_RING_PROXIMAL,
    "ring_02_r": HumanBoneSpecifications.RIGHT_RING_INTERMEDIATE,
    "ring_03_r": HumanBoneSpecifications.RIGHT_RING_DISTAL,
    "pinky_01_r": HumanBoneSpecifications.RIGHT_LITTLE_PROXIMAL,
    "pinky_02_r": HumanBoneSpecifications.RIGHT_LITTLE_INTERMEDIATE,
    "pinky_03_r": HumanBoneSpecifications.RIGHT_LITTLE_DISTAL,
}


CONFIG_DEFAULT: Final = ("MPFB2 (Default)", DEFAULT_MAPPING)
CONFIG_GAME_ENGINE: Final = ("MPFB2 (Game engine)", GAME_ENGINE_MAPPING)
