# SPDX-License-Identifier: MIT OR GPL-3.0-or-later
from collections.abc import Mapping
from typing import Final

from ..vrm1.human_bone import HumanBoneSpecification, HumanBoneSpecifications

MAPPING: Final[Mapping[str, HumanBoneSpecification]] = {
    "CC_Base_Head": HumanBoneSpecifications.HEAD,
    "CC_Base_Waist": HumanBoneSpecifications.SPINE,
    "CC_Base_Hip": HumanBoneSpecifications.HIPS,
    "CC_Base_R_Upperarm": HumanBoneSpecifications.RIGHT_UPPER_ARM,
    "CC_Base_R_Forearm": HumanBoneSpecifications.RIGHT_LOWER_ARM,
    "CC_Base_R_Hand": HumanBoneSpecifications.RIGHT_HAND,
    "CC_Base_L_Upperarm": HumanBoneSpecifications.LEFT_UPPER_ARM,
    "CC_Base_L_Forearm": HumanBoneSpecifications.LEFT_LOWER_ARM,
    "CC_Base_L_Hand": HumanBoneSpecifications.LEFT_HAND,
    "CC_Base_R_Thigh": HumanBoneSpecifications.RIGHT_UPPER_LEG,
    "CC_Base_R_Calf": HumanBoneSpecifications.RIGHT_LOWER_LEG,
    "CC_Base_R_Foot": HumanBoneSpecifications.RIGHT_FOOT,
    "CC_Base_L_Thigh": HumanBoneSpecifications.LEFT_UPPER_LEG,
    "CC_Base_L_Calf": HumanBoneSpecifications.LEFT_LOWER_LEG,
    "CC_Base_L_Foot": HumanBoneSpecifications.LEFT_FOOT,
    "CC_Base_R_Eye": HumanBoneSpecifications.RIGHT_EYE,
    "CC_Base_L_Eye": HumanBoneSpecifications.LEFT_EYE,
    "CC_Base_NeckTwist01": HumanBoneSpecifications.NECK,
    "CC_Base_L_Clavicle": HumanBoneSpecifications.LEFT_SHOULDER,
    "CC_Base_R_Clavicle": HumanBoneSpecifications.RIGHT_SHOULDER,
    "CC_Base_Spine02": HumanBoneSpecifications.UPPER_CHEST,
    "CC_Base_Spine01": HumanBoneSpecifications.CHEST,
    "CC_Base_R_ToeBase": HumanBoneSpecifications.RIGHT_TOES,
    "CC_Base_L_ToeBase": HumanBoneSpecifications.LEFT_TOES,
    "CC_Base_L_Thumb1": HumanBoneSpecifications.LEFT_THUMB_METACARPAL,
    "CC_Base_L_Finger00": HumanBoneSpecifications.LEFT_THUMB_METACARPAL,
    "CC_Base_L_Thumb2": HumanBoneSpecifications.LEFT_THUMB_PROXIMAL,
    "CC_Base_L_Finger01": HumanBoneSpecifications.LEFT_THUMB_PROXIMAL,
    "CC_Base_L_Thumb3": HumanBoneSpecifications.LEFT_THUMB_DISTAL,
    "CC_Base_L_Finger02": HumanBoneSpecifications.LEFT_THUMB_DISTAL,
    "CC_Base_L_Index1": HumanBoneSpecifications.LEFT_INDEX_PROXIMAL,
    "CC_Base_L_Finger10": HumanBoneSpecifications.LEFT_INDEX_PROXIMAL,
    "CC_Base_L_Index2": HumanBoneSpecifications.LEFT_INDEX_INTERMEDIATE,
    "CC_Base_L_Finger11": HumanBoneSpecifications.LEFT_INDEX_INTERMEDIATE,
    "CC_Base_L_Index3": HumanBoneSpecifications.LEFT_INDEX_DISTAL,
    "CC_Base_L_Finger12": HumanBoneSpecifications.LEFT_INDEX_DISTAL,
    "CC_Base_L_Mid1": HumanBoneSpecifications.LEFT_MIDDLE_PROXIMAL,
    "CC_Base_L_Finger20": HumanBoneSpecifications.LEFT_MIDDLE_PROXIMAL,
    "CC_Base_L_Mid2": HumanBoneSpecifications.LEFT_MIDDLE_INTERMEDIATE,
    "CC_Base_L_Finger21": HumanBoneSpecifications.LEFT_MIDDLE_INTERMEDIATE,
    "CC_Base_L_Mid3": HumanBoneSpecifications.LEFT_MIDDLE_DISTAL,
    "CC_Base_L_Finger22": HumanBoneSpecifications.LEFT_MIDDLE_DISTAL,
    "CC_Base_L_Ring1": HumanBoneSpecifications.LEFT_RING_PROXIMAL,
    "CC_Base_L_Finger30": HumanBoneSpecifications.LEFT_RING_PROXIMAL,
    "CC_Base_L_Ring2": HumanBoneSpecifications.LEFT_RING_INTERMEDIATE,
    "CC_Base_L_Finger31": HumanBoneSpecifications.LEFT_RING_INTERMEDIATE,
    "CC_Base_L_Ring3": HumanBoneSpecifications.LEFT_RING_DISTAL,
    "CC_Base_L_Finger32": HumanBoneSpecifications.LEFT_RING_DISTAL,
    "CC_Base_L_Pinky1": HumanBoneSpecifications.LEFT_LITTLE_PROXIMAL,
    "CC_Base_L_Finger40": HumanBoneSpecifications.LEFT_LITTLE_PROXIMAL,
    "CC_Base_L_Pinky2": HumanBoneSpecifications.LEFT_LITTLE_INTERMEDIATE,
    "CC_Base_L_Finger41": HumanBoneSpecifications.LEFT_LITTLE_INTERMEDIATE,
    "CC_Base_L_Pinky3": HumanBoneSpecifications.LEFT_LITTLE_DISTAL,
    "CC_Base_L_Finger42": HumanBoneSpecifications.LEFT_LITTLE_DISTAL,
    "CC_Base_R_Thumb1": HumanBoneSpecifications.RIGHT_THUMB_METACARPAL,
    "CC_Base_R_Finger00": HumanBoneSpecifications.RIGHT_THUMB_METACARPAL,
    "CC_Base_R_Thumb2": HumanBoneSpecifications.RIGHT_THUMB_PROXIMAL,
    "CC_Base_R_Finger01": HumanBoneSpecifications.RIGHT_THUMB_PROXIMAL,
    "CC_Base_R_Thumb3": HumanBoneSpecifications.RIGHT_THUMB_DISTAL,
    "CC_Base_R_Finger02": HumanBoneSpecifications.RIGHT_THUMB_DISTAL,
    "CC_Base_R_Index1": HumanBoneSpecifications.RIGHT_INDEX_PROXIMAL,
    "CC_Base_R_Finger10": HumanBoneSpecifications.RIGHT_INDEX_PROXIMAL,
    "CC_Base_R_Index2": HumanBoneSpecifications.RIGHT_INDEX_INTERMEDIATE,
    "CC_Base_R_Finger11": HumanBoneSpecifications.RIGHT_INDEX_INTERMEDIATE,
    "CC_Base_R_Index3": HumanBoneSpecifications.RIGHT_INDEX_DISTAL,
    "CC_Base_R_Finger12": HumanBoneSpecifications.RIGHT_INDEX_DISTAL,
    "CC_Base_R_Mid1": HumanBoneSpecifications.RIGHT_MIDDLE_PROXIMAL,
    "CC_Base_R_Finger20": HumanBoneSpecifications.RIGHT_MIDDLE_PROXIMAL,
    "CC_Base_R_Mid2": HumanBoneSpecifications.RIGHT_MIDDLE_INTERMEDIATE,
    "CC_Base_R_Finger21": HumanBoneSpecifications.RIGHT_MIDDLE_INTERMEDIATE,
    "CC_Base_R_Mid3": HumanBoneSpecifications.RIGHT_MIDDLE_DISTAL,
    "CC_Base_R_Finger22": HumanBoneSpecifications.RIGHT_MIDDLE_DISTAL,
    "CC_Base_R_Ring1": HumanBoneSpecifications.RIGHT_RING_PROXIMAL,
    "CC_Base_R_Finger30": HumanBoneSpecifications.RIGHT_RING_PROXIMAL,
    "CC_Base_R_Ring2": HumanBoneSpecifications.RIGHT_RING_INTERMEDIATE,
    "CC_Base_R_Finger31": HumanBoneSpecifications.RIGHT_RING_INTERMEDIATE,
    "CC_Base_R_Ring3": HumanBoneSpecifications.RIGHT_RING_DISTAL,
    "CC_Base_R_Finger32": HumanBoneSpecifications.RIGHT_RING_DISTAL,
    "CC_Base_R_Pinky1": HumanBoneSpecifications.RIGHT_LITTLE_PROXIMAL,
    "CC_Base_R_Finger40": HumanBoneSpecifications.RIGHT_LITTLE_PROXIMAL,
    "CC_Base_R_Pinky2": HumanBoneSpecifications.RIGHT_LITTLE_INTERMEDIATE,
    "CC_Base_R_Finger41": HumanBoneSpecifications.RIGHT_LITTLE_INTERMEDIATE,
    "CC_Base_R_Pinky3": HumanBoneSpecifications.RIGHT_LITTLE_DISTAL,
    "CC_Base_R_Finger42": HumanBoneSpecifications.RIGHT_LITTLE_DISTAL,
}

CONFIG: Final = ("Character Creator / AccuRIG", MAPPING)
