ci:
  image: buildpack-deps:noble@sha256:f9316c98dd22c69ebfc8ff437381504bf654d9ce1f18d2b637b5af7dd05cde55
  services:
    - docker:dind@sha256:1ba18449911d01f477a3fc104123c85d677addc60701b14b3fcb5381f9c4a537
  retry:
    max: 2
    when:
      - runner_system_failure
  variables:
    PATH: "${HOME}/.local/bin:${PATH}"
  before_script:
    - ./tools/install_ubuntu_packages.sh
    - ./tools/install_act.sh
    - timeout 600 sh -c 'until docker info --format "{{ .OperatingSystem }}"; do sleep 1; done'
  script:
    - act
