ci:
  image: buildpack-deps:noble
  services:
    - docker:dind
  retry:
    max: 2
    when:
      - runner_system_failure
  variables:
    PATH: "${HOME}/.local/bin:${PATH}"
  before_script:
    - ./tools/install_ubuntu_packages.sh
    - ./tools/install_act.sh
    - timeout 600 sh -c 'until docker info --format "{{ .OperatingSystem }}"; do sleep 1; done'
  script:
    - act
