ci:
  image: cimg/node:lts@sha256:5ee681fd1421b7555c4a6598689fd1258ab27e9fbeb5ccdb6ac56311e087805a
  services:
    - docker:29.4.0-dind@sha256:a6dd5322747a95cd8e3207bd8d415a8fd20ec34e9c00f06dc019cbd912013489
  retry:
    max: 2
    when:
      - runner_system_failure
  before_script:
    - git checkout -b "gitlab-ci-${CI_JOB_ID}-${CI_COMMIT_SHA}" # avoid "detached state" for act
    - sudo ./tools/install_ubuntu_packages.sh
    - ./tools/install_act.sh
    - timeout 600 sh -c 'until docker info --format "{{ .OperatingSystem }}"; do sleep 1; done'
  script:
    - ./.local/bin/act
