default: true
MD013:
  line_length: 700
MD024: false
MD028: false
MD033:
  allowed_elements:
    - a
    - img
    - small
    - span
    - u
    - DownloadLink
    - DownloadLinkJa
MD034: false
MD041: false
MD045: false
