schema_version = "1.0.0"
id = "vrm1_import_hook_example"
version = "1.0.0"
name = "VRM1 Import Hook Example"
tagline = "Example add-on"
maintainer = "Maintainer name <email@example.com>"
type = "add-on"
blender_version_min = "4.2.0"
license = ["SPDX:CC0-1.0"]
