# SPDX-License-Identifier: MIT OR GPL-3.0-or-later
class IDPropertyGroup:
    def clear(self) -> None: ...
    def get(self, key: str, default: object = None) -> object: ...
    def pop(self, key: str, default: object = None) -> object: ...
