# SPDX-License-Identifier: Apache-2.0

from typing_extensions import Self

class Response:
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> None: ...
    @property
    def ok(self) -> bool: ...
    @property
    def content(self) -> bytes: ...

def get(url: str, *, timeout: float) -> Response: ...
