# SPDX-License-Identifier: MIT OR GPL-3.0-or-later

def make_paths_absolute(execution_context: str = "EXEC_DEFAULT") -> set[str]: ...
def make_paths_relative(execution_context: str = "EXEC_DEFAULT") -> set[str]: ...
