# SPDX-License-Identifier: Apache-2.0
# https://projects.blender.org/blender/blender-addons/src/tag/v2.93.0/io_scene_gltf2/io/com/gltf2_io.py

class Material: ...
class Image: ...
class Gltf: ...

def gltf_to_dict(x: object) -> object: ...
