# SPDX-License-Identifier: MIT OR GPL-3.0-or-later
name: lint

permissions: {}

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install deb packages
        run: if sudo --non-interactive true; then sudo ./tools/install_ubuntu_packages.sh; fi
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version-file: .deno-version
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
      - name: Install UV dependencies
        run: |
          for _ in $(seq 5); do
            if uv sync; then
              break
            fi
          done
      - name: Check source code formatting
        run: |
          ./tools/format.sh
          git diff --exit-code
      - name: Check property type annotations
        run: |
          uv run python tools/property_typing.py > property_typing.log
          ./tools/format.sh
          git diff --exit-code
      - name: Install hadolint
        run: ./tools/install_hadolint.sh
      - name: Lint
        run: ./tools/lint.sh

  super-linter:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Super-Linter
        run: ./tools/super-linter.sh -e SAVE_SUPER_LINTER_SUMMARY=false

  docs:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version-file: .deno-version
      - name: Build
        run: deno task docs:build
